### ISSUE TITLE
Mac M1 usage

### ISSUE THREAD

**Issue by SignSpice** [ezflash/ezFlashCLI#19]
Currently getting this error after installing with pip on an M1 Mac:

```
INFO:root:ezFlashCLI v1.0.5
INFO:root:By using the program you accept the SEGGER J-link™ license
ERROR:root:Error loading J-Link Library:
dlopen(/opt/homebrew/lib/python3.10/site-packages/ezFlashCLI/ezFlash/../third-party/segger/libjlinkarm.dylib, 0x0006):
tried: '/opt/homebrew/lib/python3.10/site-packages/ezFlashCLI/ezFlash/../third-party/segger/libjlinkarm.dylib'
(mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')),
'/opt/homebrew/lib/python3.10/site-packages/ezFlashCLI/third-party/segger/libjlinkarm.dylib'
(mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))

Exception ignored in: <function pyjlink.__del__ at 0x1015b08b0>
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/ezFlashCLI/ezFlash/pyjlink.py", line 192, in __del__
    self.close()
  File "/opt/homebrew/lib/python3.10/site-packages/ezFlashCLI/ezFlash/pyjlink.py", line 328, in close
    self.jl.JLINKARM_Close()
AttributeError: 'NoneType' object has no attribute 'JLINKARM_Close'
```

**Comment by ezflash** [comment]
I can't promise anything as I don't have access to an M1 at the moment. The pull request #20 replaces the x86 library with the universal one. It should solve the installation issue. Will be released in 1.0.6

**Comment by ezflash** [comment]
@SignSpice, any chance you can it works by cloning the repo before the release? 

```console
git clone https://github.com/ezflash/ezFlashCLI.git
cd ezFlashCLI/
source bootstrap.sh 
python -m ezFlashCLI.cli probe
```
output should look like:

```console
INFO:root:ezFlashCLI v1.0.5.dev2+gc50f559
INFO:root:By using the program you accept the SEGGER J-link™ license
INFO:root:Smartbond chip: DA1469x
INFO:root:Flash information:
INFO:root:  - Device Id: MX25U3235F
```

if everything works fine, from the same terminal you can run 

```console
pip3 install -e .
```

That will install the package globally. When you can confirm everything is working, I can do the release. the you will just need to run

```console
pip3 install --upgrade ezFlashCLI
```

to get up to the latest release.

**Comment by SignSpice** [comment]
It works for me, thanks!
